[package]
rust = "1.51"
name = "aoc2016"
version = "0.1.0"
authors = ["Augusto Cesar <augusto.acfs@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
md-5 = "0.9.1"
hex = "0.4.2"
