name: "2020"

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths: 
      - '2020/**'
  pull_request:
    branches: 
      - master
    paths: 
      - '2020/**'

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt results
        run: ./.github/scripts/decrypt_secret.sh
        env:
          VAULT_PASS: ${{ secrets.VaultPass }}
          RESULTS_INPUT: ./2020/expected_results.gpg
          RESULTS_OUTPUT: ./2020/expected_results
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go test main.go main_test.go -v
        working-directory: ./2020