name: "2019"

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths: 
      - '2019/**'
  pull_request:
    branches: 
      - master
    paths: 
      - '2019/**'

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt results
        run: ./.github/scripts/decrypt_secret.sh
        env:
          VAULT_PASS: ${{ secrets.VaultPass }}
          RESULTS_INPUT: ./2019/expected_results.gpg
          RESULTS_OUTPUT: ./2019/src/test/resources/expected_results
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 21
      - name: Test with Gradle
        run: ./gradlew test --tests se.augustocesar.aoc2019.MainTest
        working-directory: ./2019