name: "2022"

on:
  push:
    branches: 
      - master
    paths: 
      - '2022/**'
  pull_request:
    branches: 
      - master
    paths: 
      - '2022/**'

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt results
        run: ./.github/scripts/decrypt_secret.sh
        env:
          VAULT_PASS: ${{ secrets.VaultPass }}
          RESULTS_INPUT: ./2022/src/test/resources/expected_results.gpg
          RESULTS_OUTPUT: ./2022/src/test/resources/expected_results
          
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test with Gradle
        run: ./gradlew test
        working-directory: ./2022